# Generated by Django 4.0.6 on 2022-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(max_length=50),
        ),
    ]
