# Generated by Django 4.0.6 on 2022-07-14 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to=settings.AUTH_USER_MODEL),
        ),
    ]
