# Generated by Django 4.0.6 on 2022-07-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_vehicle_vehicle_image_alter_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bodystyle',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
