# Generated by Django 4.0.6 on 2022-07-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_vehicle_bodystyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='trim',
            new_name='bodyClass',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='bodystyle',
        ),
    ]
