# Generated by Django 4.0.6 on 2022-07-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_vehicle_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image',
        ),
    ]
