# Generated by Django 4.0.6 on 2022-07-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price_currency',
        ),
        migrations.AddField(
            model_name='post',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
