# Generated by Django 4.0.6 on 2022-07-18 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_post_price_currency_post_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vehicle',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='main_app.vehicle'),
        ),
    ]
