# Generated by Django 4.0.6 on 2022-07-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_post_comment_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='content',
        ),
    ]
