# Generated by Django 4.0.6 on 2022-07-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rename_comment_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='milage',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
